version: '3'

services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:5000"
    environment:
      AWS_ACCESS_KEY_ID: AKIARZSHOXKIXMUJYZ47
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: ap-south-1
